# Generated by Django 4.1.7 on 2023-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
